name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !startsWith(github.head_ref, 'release-please--') }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - if: ${{ !startsWith(github.head_ref, 'release-please--') }}
        uses: webiny/action-conventional-commits@v1.3.0
